---
title: "`scLANE` Simulation Study - Trajectory DE Method Comparison"
subtitle: "UF Dept. of Biostatistics - Bacher Group"
author: "Jack Leary" 
date: "`r Sys.Date()`"
output:
  html_document:
    theme: journal
    highlight: tango
    code_folding: hide
    code_download: true 
    toc: true 
    toc_depth: 2
    toc_float: true
    df_print: kable
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, comment = NA, dev = "png", dpi = 320)
```

# Libraries 

```{r}
library(dplyr)
library(ggplot2)
library(targets)
```

# Helper Functions

```{r}
source("R/functions_analysis.R")
```

# Data

```{r}
tar_load(metric_table_master)
```

# Analysis

## Reference Dataset

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = ROC_AUC, y = SIM_REFERENCE, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  facet_wrap(~MODEL_TYPE) + 
  ggridges::geom_density_ridges(alpha = 0.6, scale = 0.95, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_percent()) + 
  labs(y = "Reference Dataset", x = "ROC-AUC") + 
  theme_analysis() + 
  theme(legend.position = "none")
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = F_MEASURE, y = SIM_REFERENCE, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  facet_wrap(~MODEL_TYPE) + 
  ggridges::geom_density_ridges(alpha = 0.6, scale = 0.95, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_number(accuracy = 0.1), 
                     limits = c(NA, 1)) + 
  labs(y = "Reference Dataset", x = "F-measure") + 
  theme_analysis() + 
  theme(legend.position = "none")
```

## Runtime

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS), 
         RUNTIME_MINS = RUNTIME_HOURS * 60) %>% 
  ggplot(aes(x = N_CELLS, y = RUNTIME_MINS, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_number(accuracy = 1, suffix = "min")) + 
  labs(x = "Cells", y = "Runtime") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(RUNTIME_MINS = RUNTIME_HOURS * 60, 
         GENES_PER_MIN = N_GENES / RUNTIME_MINS) %>% 
  ggplot(aes(x = N_CELLS, y = GENES_PER_MIN, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_smooth(method = "lm", alpha = 0.25) + 
  scale_y_continuous(labels = scales::label_number(accuracy = 1)) + 
  labs(x = "Cells", y = "Genes per Minute") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 0, linewidth = 2)))
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(RUNTIME_MINS = RUNTIME_HOURS * 60, 
         GENES_PER_MIN = N_GENES / RUNTIME_MINS) %>% 
  ggplot(aes(x = GENES_PER_MIN, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_number(accuracy = 1)) + 
  labs(x = "Genes per Minute", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

## Memory Usage

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS), 
         MEM_USED_GB = MEM_USED / 1000) %>% 
  ggplot(aes(x = N_CELLS, y = MEM_USED_GB, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_number(suffix = "gb")) + 
  labs(x = "Cells", y = "Memory Usage") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(MEM_USED_GB = MEM_USED / 1000) %>% 
  ggplot(aes(x = MEM_USED_GB, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_number(suffix = "gb")) + 
  labs(x = "Memory Usage", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

## Predictive Performance

### F-measure 

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = N_CELLS, y = F_MEASURE, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_number(accuracy = 0.1)) + 
  labs(x = "Cells", y = "F-measure") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = F_MEASURE, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_number(accuracy = 0.1)) + 
  labs(x = "F-measure", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

### Balanced Accuracy 

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = N_CELLS, y = BAL_ACCURACY, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Cells", y = "Balanced Accuracy") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = BAL_ACCURACY, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Balanced Accuracy", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

### Recall

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = N_CELLS, y = RECALL, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Cells", y = "Recall") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = RECALL, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Recall", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

### Accuracy

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = N_CELLS, y = ACCURACY)) + 
  geom_boxplot(aes(color = MODEL_TYPE)) + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Cells", y = "Accuracy") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = ACCURACY, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Accuracy", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

### ROC-AUC

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = N_CELLS, y = ROC_AUC, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Cells", y = "ROC-AUC") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = ROC_AUC, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "ROC-AUC", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM")) %>% 
  pull(ROC_CURVE) %>% 
  purrr::reduce(rbind) %>% 
  left_join((distinct(metric_table_master, DATASET_NAME, N_CELLS)), 
            by = c("dataset" = "DATASET_NAME")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, group = dataset, color = N_CELLS)) + 
  facet_wrap(~paste0("Cells: ", N_CELLS)) + 
  geom_segment(x = 0, xend = 0, y = 1, yend = 1, color = "black", linetype = "dashed", size = 1) + 
  geom_line(size = 1, alpha = 0.8) + 
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + 
  labs(x = "1 - Specificity", 
      y = "Sensitivity", 
      color = "Cells", 
      title = "scLANE - GLM") + 
  theme_analysis() +  
  guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1)))
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("tradeSeq")) %>% 
  pull(ROC_CURVE) %>% 
  purrr::reduce(rbind) %>% 
  left_join((distinct(metric_table_master, DATASET_NAME, N_CELLS)), 
            by = c("dataset" = "DATASET_NAME")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = 1 - specificity, y = sensitivity, group = dataset, color = N_CELLS)) + 
  facet_wrap(~paste0("Cells: ", N_CELLS)) + 
  geom_segment(x = 0, xend = 0, y = 1, yend = 1, color = "black", linetype = "dashed", size = 1) + 
  geom_line(size = 1, alpha = 0.8) + 
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) + 
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) + 
  labs(x = "1 - Specificity", 
      y = "Sensitivity", 
      color = "Cells", 
      title = "tradeSeq") + 
  theme_analysis() + 
  guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1)))
```

### PR-AUC

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = N_CELLS, y = AUC_PR, color = MODEL_TYPE)) + 
  geom_boxplot() + 
  scale_y_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "Cells", y = "PR-AUC") + 
  theme_analysis() + 
  theme(legend.title = element_blank())
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM", "tradeSeq")) %>% 
  ggplot(aes(x = AUC_PR, color = MODEL_TYPE, fill = MODEL_TYPE)) + 
  geom_density(alpha = 0.3, linewidth = 1) + 
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) + 
  labs(x = "PR-AUC", y = "Density") + 
  theme_analysis() + 
  theme(legend.title = element_blank()) + 
  guides(color = guide_legend(override.aes = list(alpha = 1, color = "white", linewidth = 0.5)))
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("scLANE - GLM")) %>% 
  pull(PR_CURVE) %>% 
  purrr::reduce(rbind) %>% 
  left_join((distinct(metric_table_master, DATASET_NAME, N_CELLS)), 
            by = c("dataset" = "DATASET_NAME")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = recall, y = precision, group = dataset, color = N_CELLS)) + 
  facet_wrap(~paste0("Cells: ", N_CELLS)) + 
  geom_segment(x = 0, xend = 1, y = 1, yend = 0, color = "black", linetype = "dashed", size = 1) + 
  geom_line(size = 1, alpha = 0.8) + 
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent_format(accuracy = 1)) +
  labs(x = "Recall", 
       y = "Precision", 
       color = "Cells", 
       title = "scLANE - GLM") + 
  theme_analysis() + 
  guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1)))
```

```{r}
filter(metric_table_master, 
       MODEL_TYPE %in% c("tradeSeq")) %>% 
  pull(PR_CURVE) %>% 
  purrr::reduce(rbind) %>% 
  left_join((distinct(metric_table_master, DATASET_NAME, N_CELLS)), 
            by = c("dataset" = "DATASET_NAME")) %>% 
  mutate(N_CELLS = round(N_CELLS, digits = -1), 
         N_CELLS = as.factor(N_CELLS)) %>% 
  ggplot(aes(x = recall, y = precision, group = dataset, color = N_CELLS)) + 
  facet_wrap(~paste0("Cells: ", N_CELLS)) + 
  geom_segment(x = 0, xend = 1, y = 1, yend = 0, color = "black", linetype = "dashed", size = 1) + 
  geom_line(size = 1, alpha = 0.8) + 
  scale_x_continuous(labels = scales::percent_format(accuracy = 1)) +
  scale_y_continuous(limits = c(0, 1), labels = scales::percent_format(accuracy = 1)) +
  labs(x = "Recall", 
       y = "Precision", 
       color = "Cells", 
       title = "tradeSeq") + 
  theme_analysis() + 
  guides(color = guide_legend(override.aes = list(linewidth = 2, alpha = 1)))
```

# Session Info

```{r}
sessioninfo::session_info()
```
